//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTKhan_Dentist
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Appointment()
        {
            this.PatientTreatments = new HashSet<PatientTreatment>();
        }
    
        public int Appointment_ID { get; set; }
        public int Patient_ID { get; set; }
        public int Employee_ID { get; set; }
        public int Timeslot_ID { get; set; }
        public System.DateTime Appointment_Date { get; set; }
        public string Appointment_Notes { get; set; }
        public Nullable<System.DateTime> Appointment_Follow_Up_Date { get; set; }
        public string Appointment_Status { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Patient Patient { get; set; }
        public virtual Timeslot Timeslot { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientTreatment> PatientTreatments { get; set; }
    }
}
