//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTKhan_Dentist
{
    using System;
    using System.Collections.Generic;
    
    public partial class Availability_Override
    {
        public int Override_ID { get; set; }
        public System.DateTime Target_Date { get; set; }
        public Nullable<int> Timeslot_ID { get; set; }
        public bool Is_Full_Day { get; set; }
        public string Reason { get; set; }
        public Nullable<int> Employee_ID { get; set; }
    
        public virtual Timeslot Timeslot { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Timeslot Timeslot1 { get; set; }
    }
}
