//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTKhan_Dentist
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public int invoice_id { get; set; }
        public int appointment_id { get; set; }
        public Nullable<int> payment_id { get; set; }
        public System.DateTime invoice_date { get; set; }
        public decimal invoice_total_amount { get; set; }
        public string invoice_status { get; set; }
        public decimal invoice_balance_due { get; set; }
    }
}
