//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTKhan_Dentist
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientTreatment
    {
        public int PatientTreatment_ID { get; set; }
        public int Appointment_ID { get; set; }
        public Nullable<int> TreatmentID { get; set; }
        public string Diagnosis { get; set; }
        public string Diagnosis_Notes { get; set; }
        public string Treatment_Notes { get; set; }
        public Nullable<System.DateTime> Date_Recorded { get; set; }
    
        public virtual Treatment Treatment { get; set; }
        public virtual Appointment Appointment { get; set; }
    }
}
