//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTKhan_Dentist
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prescription
    {
        public int Prescription_ID { get; set; }
        public int PatientTreatment_ID { get; set; }
        public int MedicineID { get; set; }
        public string Quantity { get; set; }
        public string Dosage_Instructions { get; set; }
        public Nullable<System.DateTime> Date_Issued { get; set; }
    
        public virtual Medicine Medicine { get; set; }
    }
}
