//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTKhan_Dentist
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffMessage
    {
        public int Message_ID { get; set; }
        public string Sender_Name { get; set; }
        public string Message_Text { get; set; }
        public Nullable<System.DateTime> Sent_At { get; set; }
    }
}
