//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTKhan_Dentist
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemLink
    {
        public int Link_ID { get; set; }
        public string Source_App { get; set; }
        public string Target_App { get; set; }
        public string Reference_No { get; set; }
        public Nullable<int> Patient_ID { get; set; }
        public Nullable<int> Appointment_ID { get; set; }
        public string Message_Type { get; set; }
        public string Message_Text { get; set; }
        public Nullable<System.DateTime> Created_At { get; set; }
        public Nullable<bool> Is_Read { get; set; }
    }
}
