//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------
namespace MTKhan_Dentist.Account
{
    public partial class Register
    {
        /// <summary>
        /// BtnSelectPatient control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button BtnSelectPatient;

        /// <summary>
        /// BtnSelectStaff control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button BtnSelectStaff;

        /// <summary>
        /// ErrorMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder ErrorMessage;

        /// <summary>
        /// FailureText control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal FailureText;

        // ==================== Patient Controls ====================

        /// <summary>
        /// PatientPanel control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel PatientPanel;

        /// <summary>
        /// PatientFirstName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox PatientFirstName;

        /// <summary>
        /// PatientLastName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox PatientLastName;

        /// <summary>
        /// PatientPhone control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox PatientPhone;

        /// <summary>
        /// PatientEmail control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox PatientEmail;

        /// <summary>
        /// PatientDOB control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox PatientDOB;

        /// <summary>
        /// PatientAllergies control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox PatientAllergies;

        /// <summary>
        /// PatientStreet control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox PatientStreet;

        /// <summary>
        /// PatientSuburb control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox PatientSuburb;

        /// <summary>
        /// PatientCity control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox PatientCity;

        /// <summary>
        /// PatientCode control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox PatientCode;

        /// <summary>
        /// BtnRegisterPatient control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button BtnRegisterPatient;

        // ==================== Staff Controls ====================

        /// <summary>
        /// StaffPanel control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel StaffPanel;

        /// <summary>
        /// StaffFirstName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox StaffFirstName;

        /// <summary>
        /// StaffLastName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox StaffLastName;

        /// <summary>
        /// StaffRole control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList StaffRole;

        /// <summary>
        /// StaffPhone control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox StaffPhone;

        /// <summary>
        /// StaffEmail control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox StaffEmail;

        /// <summary>
        /// StaffNationalID control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox StaffNationalID;

        /// <summary>
        /// StaffAge control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox StaffAge;

        /// <summary>
        /// StaffUsername control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox StaffUsername;

        /// <summary>
        /// StaffPassword control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox StaffPassword;

        /// <summary>
        /// StaffConfirmPassword control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox StaffConfirmPassword;

        /// <summary>
        /// BtnRegisterStaff control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button BtnRegisterStaff;

        /// <summary>
        /// LoginHyperLink control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink LoginHyperLink;
    }
}
